# Generated by Django 3.0.4 on 2020-03-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuck', '0002_fuckuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
