# Generated by Django 3.0.4 on 2020-03-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuck', '0003_conversation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
