# Generated by Django 3.0.4 on 2020-03-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuck', '0006_auto_20200315_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
    ]
